language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  
script:
  - jdk_switcher use oraclejdk8
  - javac *.java
  - jdk_switcher use oraclejdk7
  - javac *.java
  - jdk_switcher use openjdk6
  - javac *.java